### ISSUE TITLE
Design file generate unnecessary filed

### ISSUE THREAD

**Issue by tcnksm** [tcnksm/gcli#51]
Currently `design` command generates unnecessary filed which is used for internal connection,

```toml
Name = "xxxx"
Owner = "tcnksm"
Version = "0.1.0"
Description = ""
Framework = "mitchellh_cli"

[[Commands]]
  Name = ""
  FunctionName = ""
  Synopsis = ""
  Help = ""
```

We don't need `FunctionName` field ..
